spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://47.120.52.242:3308/digital_meal_tickets?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true

  jpa:
    hibernate:
      ddl-auto: none  # 不自动创建/更新表结构
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true      # 显示SQL语句
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true  # 格式化SQL输出
        globally_quoted_identifiers: true  # 强制使用引号包围所有标识符

  # Redis配置
#  redis:
#    host: localhost
#    port: 6379
#    database: 0  # 使用数据库0
#    timeout: 3000ms

  # 应用配置
  application:
    name: digital-meal-ticket-backend

# 服务器配置
server:
  port: 8081
  servlet:
    context-path: /api

# 日志配置
logging:
  level:
    com.Digital.meal.tickets.demo: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
